
CREATE TABLE CLIENTE(
POSTIZA_CLIENTE	VARCHAR(40),
E_MAIL	VARCHAR(40) NOT NULL,
DIRECCION VARCHAR(40) NOT NULL,
TELEFONO VARCHAR(16) NOT NULL,
CONSTRAINT PK_CLIENTE PRIMARY KEY (POSTIZA_CLIENTE)
);

CREATE TABLE PERSONA_NATURAL(
CEDULA	VARCHAR(14),
NOMBRE	VARCHAR(40) NOT NULL,
POSTIZA_CLIENTE	VARCHAR(40),
CONSTRAINT PK_PERSONA_NATURAL PRIMARY KEY (CEDULA)
--FOREIGN KEY (POSTIZA_CLIENTE) REFERENCES CLIENTE
);

CREATE TABLE PERSONA_JURIDICA(
RIF	VARCHAR(14),
RAZON_SOCIAL	VARCHAR(40) NOT NULL,
POSTIZA_CLIENTE	VARCHAR(40),
CONSTRAINT PK_PERSONA_JURIDICA PRIMARY KEY (RIF)
--FOREIGN KEY (POSTIZA_CLIENTE) REFERENCES CLIENTE
);

CREATE TABLE DIRECCION_POSTAL(
ESTADO	VARCHAR(40),
CIUDAD	VARCHAR(40),	
ZONA_POSTAL	VARCHAR(40),
CODIGO_POSTAL	VARCHAR(40) NOT NULL,
CONSTRAINT PK_DIRECCION_POSTAL PRIMARY KEY (ESTADO, CIUDAD, ZONA_POSTAL)
);

CREATE TABLE INMUEBLE(
ESTADO	VARCHAR(40),
CIUDAD	VARCHAR(40),
ZONA_POSTAL	VARCHAR(40),
UNIDAD VARCHAR(40),
TIPO_CONSTRUCCION VARCHAR(40),
TIPO_CALLE VARCHAR(40),
NOMBRE_CALLE VARCHAR(40),
ID_CONSTRUCCION VARCHAR(40),
POSTIZA_CLIENTE VARCHAR(40) NOT NULL,
ID_SOLICITUD VARCHAR(40) NOT NULL,
POSTIZA_OFICINA_REGISTRO VARCHAR(40) NOT NULL,
TIPO_JUSTIFICATIVO VARCHAR(40) NOT NULL,
FOLIO VARCHAR(40) NOT NULL,
FECHA VARCHAR(40) NOT NULL,
LIBRO VARCHAR(40) NOT NULL,
TOMO VARCHAR(40) NOT NULL,
CONSTRAINT PK_INMUEBLE PRIMARY KEY (ESTADO, CIUDAD, ZONA_POSTAL, TIPO_CONSTRUCCION, TIPO_CALLE, NOMBRE_CALLE, ID_CONSTRUCCION)
--FOREIGN KEY (ESTADO, CIUDAD, ZONA_POSTAL) REFERENCES DIRECCION_POSTAL,
--FOREIGN KEY (POSTIZA_CLIENTE) REFERENCES CLIENTE
);

CREATE TABLE PLAN(
POSTIZA_PLAN VARCHAR(40),
CONSTRAINT PK_PLAN PRIMARY KEY (POSTIZA_PLAN)
);

CREATE TABLE PLAN_TV(
NOMBRE_PLAN_TV VARCHAR(40),
RENTA_BASICA_TV VARCHAR(40) NOT NULL,
POSTIZA_PLAN VARCHAR(40),
CONSTRAINT PK_PLAN_TV PRIMARY KEY (NOMBRE_PLAN_TV)
--FOREIGN KEY	(POSTIZA_PLAN) REFERENCES PLAN,
);

CREATE TABLE PLAN_INTERNET(
NOMBRE_PLAN_INTERNET VARCHAR(40),
RENTA_BASICA_INTERNET VARCHAR(40) NOT NULL,
POSTIZA_PLAN VARCHAR(40),
CONSTRAINT PK_PLAN_INTERNET PRIMARY KEY (NOMBRE_PLAN_INTERNET)
--FOREIGN KEY (POSTIZA_PLAN) REFERENCES PLAN
);

CREATE TABLE HORA_EXTRA(
AÑO NUMERIC(4),
MES NUMERIC(2),
HORA VARCHAR(5),
DIA NUMERIC(2),
COSTO NUMERIC(40) NOT NULL,
NOMBRE_PLAN_INTERNET VARCHAR(40) NOT NULL,
CONSTRAINT PK_HORA_EXTRA PRIMARY KEY (AÑO, MES, HORA, DIA)
);

CREATE TABLE CANAL(
NOMBRE_CANAL VARCHAR(40),
TIPO_CANAL VARCHAR(40) NOT NULL,
CONSTRAINT PK_CANAL PRIMARY KEY(NOMBRE_CANAL)
);

CREATE TABLE TIENE_ASOCIADO(
NOMBRE_PLAN_TV VARCHAR(40),
NOMBRE_CANAL VARCHAR(40),
CONSTRAINT PK_TIENE_ASOCIADO PRIMARY KEY (NOMBRE_PLAN_TV, NOMBRE_CANAL)
--FOREIGN KEY (NOMBRE_PLAN_TV) REFERENCES PLAN_TV,
--FOREIGN KEY (NOMBRE_CANAL) REFERENCES CANAL
);

CREATE TABLE PROGRAMA(
NOMBRE_PROGRAMA VARCHAR(40),
HORARIO VARCHAR(40) NOT NULL,
COSTO_PROGRAMA NUMERIC(40) NOT NULL,
CONSTRAINT PK_PROGRAMA PRIMARY KEY (NOMBRE_PROGRAMA)
);

CREATE TABLE LLEVA(
NOMBRE_PLAN_TV VARCHAR(40),
NOMBRE_PROGRAMA VARCHAR(40),
CONSTRAINT PK_LLEVA PRIMARY KEY (NOMBRE_PLAN_TV, NOMBRE_PROGRAMA)
--FOREIGN KEY (NOMBRE_PLAN_TV) REFERENCES PLAN_TV,
--FOREIGN KEY (NOMBRE_PROGRAMA) REFERENCES PROGRAMA
);

CREATE TABLE TURNO(
NOMBRE_TURNO VARCHAR(40),
HORAS VARCHAR(11) NOT NULL,
CONSTRAINT PK_TURNO PRIMARY KEY (NOMBRE_TURNO)
);

CREATE TABLE PERMITE(
NOMBRE_PLAN_INTERNET VARCHAR(40),
NOMBRE_TURNO VARCHAR(40),
CONSTRAINT PK_PERMITE PRIMARY KEY (NOMBRE_PLAN_INTERNET, NOMBRE_TURNO)
--FOREIGN KEY (NOMBRE_PLAN_INTERNET) REFERENCES PLAN_INTERNET,
--FOREIGN KEY (NOMBRE_TURNO) REFERENCES TURNO
);

CREATE TABLE METODO_PAGO(
POSTIZA_METODO_PAGO VARCHAR(40),
MONTO NUMERIC(40) NOT NULL,
CONSTRAINT PK_METODO_PAGO PRIMARY KEY (POSTIZA_METODO_PAGO)
);

CREATE TABLE CHEQUE(
NUMERO_CHEQUE NUMERIC(40),
BANCO_CHEQUE VARCHAR(40),
POSTIZA_METODO_PAGO VARCHAR(40),
CLAVE_CONFORMACION VARCHAR(40) NOT NULL,
NOMBRA_TITULAR_CUENTA VARCHAR(40) NOT NULL,
CUENTA_ASOCIADA VARCHAR(40) NOT NULL,
CI_TITULAR_CUENTA NUMERIC(8) NOT NULL,
ID_FACTURA VARCHAR(40) NOT NULL,
CONSTRAINT PK_CHEQUE PRIMARY KEY (NUMERO_CHEQUE, BANCO_CHEQUE, ID_FACTURA)
--FOREIGN KEY (POSTIZA_METODO_PAGO) REFERENCES METODO_PAGO
--FOREIGN KEY (ID_FACTURA) REFERENCES PAGO_PERSONAL
);

CREATE TABLE EFECTIVO(
MONTO_EFECTIVO NUMERIC(40),
ID_FACTURA VARCHAR(40) NOT NULL,
POSTIZA_METODO_PAGO VARCHAR(40), 
CONSTRAINT PK_EFECTIVO PRIMARY KEY (MONTO_EFECTIVO, ID_FACTURA)
--FOREIGN KEY (ID_FACTURA) REFERENCES PAGO_PERSONAL,
--FOREIGN KEY (POSTIZA_METODO_PAGO) REFERENCES METODO_PAGO
);

CREATE TABLE TARJETA(
NUMERO_TARJETA NUMERIC(18),
BANCO_TARJETA VARCHAR(40),
ID_FACTURA VARCHAR(40) NOT NULL,
TIPO_TARJETA VARCHAR(7), --CHECK(TIPO_TARJETA IN ('CREDITO','DEBITO')),
CI_TARJETAHABIENTE NUMERIC(8) NOT NULL,
NOMBRE_TARJETAHABIENTE VARCHAR(40) NOT NULL,
POSTIZA_METODO_PAGO VARCHAR(40),
CONSTRAINT PK_TARJETA PRIMARY KEY(NUMERO_TARJETA, BANCO_TARJETA, TIPO_TARJETA, ID_FACTURA)
--FOREIGN KEY(POSTIZA_METODO_PAGO) REFERENCES METODO_PAGO
);

CREATE TABLE PAGO_DOMICILIADO(
ID_FACTURA VARCHAR(40),
ENTIDAD_BANCARIA VARCHAR(40) NOT NULL,
NRO_IDENTIFICADOR NUMERIC(40) NOT NULL,
TIPO_INSTRUMENTO VARCHAR(18) NOT NULL, --CHECK (TIPO_INSTRUMENTO IN ('TARJETA DE CREDITO', 'CUENTA BANCARIA')),
MONTO_RECONEXION NUMERIC(40),
ID_CONTRATO VARCHAR(40),
CONSTRAINT PK_PAGO_DOMICILIADO PRIMARY KEY (ID_FACTURA)
--FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA,
--FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO
);

CREATE TABLE PAGO_PERSONAL(
ID_FACTURA VARCHAR(40),
PLATAFORMA_PAGO VARCHAR(40) NOT NULL,
MONTO_RECONEXION NUMERIC(40),
ID_CONTRATO VARCHAR(40),
CONSTRAINT PK_PAGO_PERSONAL PRIMARY KEY (ID_FACTURA)
--FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA,
--FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO
);

CREATE TABLE CONTRATO(
ID_CONTRATO VARCHAR(40),
DIA NUMERIC(2) NOT NULL, --CHECK (DIA>0 AND DIA<32),
MES NUMERIC(2) NOT NULL, --CHECK (MES>0 AND MES<13),
AÑO  NUMERIC(4) NOT NULL,
ID_SOLICITUD  VARCHAR(40) NOT NULL,
CONSTRAINT PK_CONTRATO PRIMARY KEY (ID_CONTRATO)
--FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE
);

CREATE TABLE VIRTUAL(
ID_SOLICITUD VARCHAR(40),
CONSTRAINT PK_VIRTUAL PRIMARY KEY (ID_SOLICITUD)
--FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE
);

CREATE TABLE LOCAL(
ID_SOLICITUD VARCHAR(40),
ID_OFICINA VARCHAR(40),
ID_OPERADOR VARCHAR(40),
CONSTRAINT PK_LOCAL PRIMARY KEY (ID_SOLICITUD)
--FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE
);

CREATE TABLE PARA_OBTENER(
POSTIZA_PLAN VARCHAR(40),
ID_SOLICITUD VARCHAR(40),
CONSTRAINT PK_PARA_OBTENER PRIMARY KEY (POSTIZA_PLAN, ID_SOLICITUD)
--FOREIGN KEY (POSTIZA_PLAN) REFERENCES PLAN,
--FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE
);

CREATE TABLE OFICINA_REGISTRO(
POSTIZA_OFICINA_REGISTRO VARCHAR(40),
CONSTRAINT PK_OFICINA_REGISTRO PRIMARY KEY (POSTIZA_OFICINA_REGISTRO)
);

CREATE TABLE NOTARIA(
ID_NOTARIA VARCHAR(40),
POSTIZA_OFICINA_REGISTRO VARCHAR(40),
CONSTRAINT PK_NOTARIA PRIMARY KEY (ID_NOTARIA)
--FOREIGN KEY (POSTIZA_OFICINA_REGISTRO) REFERENCES OFICINA_REGISTRO
);

CREATE TABLE REGISTRO_PUBLICO(
ID_REGISTRO VARCHAR(40),
POSTIZA_OFICINA_REGISTRO VARCHAR(40),
CONSTRAINT PK_REGISTRO_PUBLICO PRIMARY KEY (ID_REGISTRO)
--FOREIGN KEY (POSTIZA_OFICINA_REGISTRO) REFERENCES OFICINA_REGISTRO
);

