ALTER TABLE PERSONA_NATURAL
ADD CONSTRAINT FK_PERSONA_NATURAL_CLIENTE FOREIGN KEY (POSTIZA_CLIENTE) REFERENCES CLIENTE;

ALTER TABLE PERSONA_NATURAL
ADD CONSTRAINT AK_PERSONA_NATURAL UNIQUE(POSTIZA_CLIENTE);

ALTER TABLE PERSONA_JURIDICA
ADD CONSTRAINT FK_PERSONA_JURIDICA_CLIENTE FOREIGN KEY (POSTIZA_CLIENTE) REFERENCES CLIENTE;

ALTER TABLE PERSONA_JURIDICA
ADD CONSTRAINT AK_PERSONA_JURIDICA UNIQUE(POSTIZA_CLIENTE);

ALTER TABLE INMUEBLE
ADD CONSTRAINT FK_INMUEBLE_DIRECCION_POSTAL FOREIGN KEY (ESTADO, CIUDAD, ZONA_POSTAL) REFERENCES DIRECCION_POSTAL;

ALTER TABLE INMUEBLE
ADD CONSTRAINT FK_INMUEBLE_CLIENTE FOREIGN KEY (POSTIZA_CLIENTE) REFERENCES CLIENTE;

ALTER TABLE INMUEBLE
ADD CONSTRAINT AK_INMUEBLE UNIQUE(POSTIZA_CLIENTE);

ALTER TABLE INMUEBLE
ADD CONSTRAINT AK_INMUEBLE1 UNIQUE(ID_SOLICITUD);

ALTER TABLE INMUEBLE
ADD CONSTRAINT AK_INMUEBLE2 UNIQUE(POSTIZA_OFICINA_REGISTRO);

ALTER TABLE INMUEBLE
ADD CONSTRAINT AK_INMUEBLE3 UNIQUE(FOLIO, FECHA, LIBRO, TOMO);

ALTER TABLE PLAN_TV
ADD CONSTRAINT FK_PLAN_TV_PLAN FOREIGN KEY (POSTIZA_PLAN) REFERENCES PLAN;

ALTER TABLE PLAN_TV
ADD CONSTRAINT DOM_PLAN_TV_NOMBRE_PLAN_TV CHECK (NOMBRE_PLAN_TV IN ('Básico','Entretenido','Súper'));

ALTER TABLE PLAN_TV
ADD CONSTRAINT AK_PLAN_TV UNIQUE(POSTIZA_PLAN);

ALTER TABLE PLAN_INTERNET
ADD CONSTRAINT FK_PLAN_INTERNET_PLAN FOREIGN KEY (POSTIZA_PLAN) REFERENCES PLAN;

ALTER TABLE PLAN_INTERNET
ADD CONSTRAINT DOM_PLAN_INTERNET_NOMBRE_PLAN_INTERNET CHECK (NOMBRE_PLAN_INTERNET IN ('Restringido','Intermedio','Extendido', 'Ilimitado'));

ALTER TABLE PLAN_INTERNET
ADD CONSTRAINT AK_PLAN_INTERNET UNIQUE(POSTIZA_PLAN);

ALTER TABLE HORA_EXTRA
ADD CONSTRAINT FK_HORA_EXTRA_PLAN_INTERNET FOREIGN KEY (NOMBRE_PLAN_INTERNET) REFERENCES PLAN_INTERNET;

ALTER TABLE HORA_EXTRA
ADD CONSTRAINT AK_HORA_EXTRA UNIQUE(NOMBRE_PLAN_INTERNET);

ALTER TABLE HORA_EXTRA
ADD CONSTRAINT DOM_HORA_EXTRA_MES CHECK (MES >= 1 and MES <= 12);

ALTER TABLE HORA_EXTRA
ADD CONSTRAINT DOM_HORA_EXTRA_DIA CHECK (DIA >= 1 and DIA <= 31);

ALTER TABLE CANAL
ADD CONSTRAINT DOM_CANAL_NOMBRE_CANAL CHECK (TIPO_CANAL IN ('Regular', 'Premium'));

ALTER TABLE TIENE_ASOCIADO
ADD CONSTRAINT FK_TIENE_ASOCIADO_PLAN_TV FOREIGN KEY (NOMBRE_PLAN_TV) REFERENCES PLAN_TV;

ALTER TABLE TIENE_ASOCIADO
ADD  CONSTRAINT FK_TIENE_ASOCIADO_CANAL FOREIGN KEY (NOMBRE_CANAL) REFERENCES CANAL;

ALTER TABLE LLEVA 
ADD CONSTRAINT FK_LLEVA_PLAN_TV FOREIGN KEY (NOMBRE_PLAN_TV) REFERENCES PLAN_TV;

ALTER TABLE LLEVA 
ADD CONSTRAINT FK_LLEVA_PROGRAMA FOREIGN KEY (NOMBRE_PROGRAMA) REFERENCES PROGRAMA;

ALTER TABLE TURNO 
ADD CONSTRAINT DOM_TURNO_NOMBRE_TURNO CHECK (NOMBRE_TURNO IN ('Vespertino', 'Matutino', 'Nocturno'));

ALTER TABLE PERMITE
ADD CONSTRAINT FK_PERMITE_PLAN_INTERNET FOREIGN KEY (NOMBRE_PLAN_INTERNET) REFERENCES PLAN_INTERNET;

ALTER TABLE PERMITE
ADD CONSTRAINT FK_PERMITE_TURNO FOREIGN KEY (NOMBRE_TURNO) REFERENCES TURNO;

ALTER TABLE CHEQUE
ADD CONSTRAINT FK_CHEQUE_METODO_PAGO FOREIGN KEY (POSTIZA_METODO_PAGO) REFERENCES METODO_PAGO;

ALTER TABLE CHEQUE
ADD CONSTRAINT AK_CHEQUE UNIQUE(POSTIZA_METODO_PAGO);

ALTER TABLE CHEQUE
ADD CONSTRAINT AK_CHEQUE1 UNIQUE(CLAVE_CONFORMACION);

ALTER TABLE CHEQUE
ADD CONSTRAINT FK_CHEQUE_PAGO_PERSONAL FOREIGN KEY (ID_FACTURA) REFERENCES PAGO_PERSONAL;

ALTER TABLE EFECTIVO
ADD CONSTRAINT FK_EFECTIVO_PAGO_PERSONAL FOREIGN KEY (ID_FACTURA) REFERENCES PAGO_PERSONAL;

ALTER TABLE EFECTIVO
ADD CONSTRAINT FK_EFECTIVO_METODO_PAGO FOREIGN KEY (POSTIZA_METODO_PAGO) REFERENCES METODO_PAGO;

ALTER TABLE EFECTIVO
ADD CONSTRAINT AK_EFECTIVO UNIQUE(POSTIZA_METODO_PAGO);

ALTER TABLE TARJETA
ADD CONSTRAINT FK_TARJETA_METODO_PAGO FOREIGN KEY (POSTIZA_METODO_PAGO) REFERENCES METODO_PAGO;

ALTER TABLE TARJETA
ADD CONSTRAINT AK_TARJETA UNIQUE(POSTIZA_METODO_PAGO);

ALTER TABLE TARJETA
ADD CONSTRAINT FK_TARJETA_PAGO_PERSONAL FOREIGN KEY (ID_FACTURA) REFERENCES PAGO_PERSONAL;

ALTER TABLE TARJETA
ADD CONSTRAINT DOM_TARJETA_TIPO_TARJETA CHECK (TIPO_TARJETA IN ('Debito', 'Crédito'));

ALTER TABLE PAGO_DOMICILIADO
ADD CONSTRAINT FK_PAGO_DOMICILIADO_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO;

ALTER TABLE PAGO_DOMICILIADO
ADD CONSTRAINT AK_PAGO_DOMICILIADO UNIQUE(ID_CONTRATO);

ALTER TABLE PAGO_DOMICILIADO
ADD CONSTRAINT DOM_PAGO_DOMICILIADO_TIPO_INSTRUMENTO CHECK (TIPO_INSTRUMENTO IN ('tarjeta de crédito', 'cuenta bancaria'));

ALTER TABLE PAGO_PERSONAL
ADD CONSTRAINT FK_PAGO_PERSONAL_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO;

ALTER TABLE PAGO_PERSONAL
ADD CONSTRAINT AK_PAGO_PERSONAL UNIQUE(ID_CONTRATO);

ALTER TABLE PAGO_PERSONAL
ADD CONSTRAINT DOM_PAGO_PERSONAL_PLATAFORMA_PAGO CHECK (PLATAFORMA_PAGO IN ('página web', 'oficina comercial'));

ALTER TABLE CONTRATO
ADD CONSTRAINT FK_CONTRATO_SOLICITUD FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE(ID_SOLICITUD);

ALTER TABLE CONTRATO
ADD CONSTRAINT AK_CONTRATO UNIQUE(ID_SOLICITUD);

ALTER TABLE CONTRATO
ADD CONSTRAINT DOM_CONTRATO_MES CHECK (MES > 0 AND MES < 13);

ALTER TABLE CONTRATO
ADD CONSTRAINT DOM_CONTRATO_DIA CHECK (DIA > 0 AND DIA < 32);

ALTER TABLE VIRTUAL
ADD CONSTRAINT FK_VIRTUAL_INMUEBLE FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE(ID_SOLICITUD);

ALTER TABLE LOCAL
ADD CONSTRAINT FK_LOCAL_INMUEBLE FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE(ID_SOLICITUD);

ALTER TABLE PARA_OBTENER
ADD CONSTRAINT FK_PARA_OBTENER_PLAN FOREIGN KEY (POSTIZA_PLAN) REFERENCES PLAN(POSTIZA_PLAN);

ALTER TABLE PARA_OBTENER
ADD CONSTRAINT FK_PARA_OBTENER_INMUEBLE FOREIGN KEY (ID_SOLICITUD) REFERENCES INMUEBLE(ID_SOLICITUD);

ALTER TABLE NOTARIA
ADD CONSTRAINT FK_NOTARIA_OFICINA_REGISTRO FOREIGN KEY (POSTIZA_OFICINA_REGISTRO) REFERENCES OFICINA_REGISTRO(POSTIZA_OFICINA_REGISTRO);

ALTER TABLE NOTARIA
ADD CONSTRAINT AK_NOTARIA UNIQUE(POSTIZA_OFICINA_REGISTRO);

ALTER TABLE REGISTRO_PUBLICO
ADD CONSTRAINT FK_REGISTRO_PUBLICO_OFICINA_REGISTRO FOREIGN KEY (POSTIZA_OFICINA_REGISTRO) REFERENCES OFICINA_REGISTRO(POSTIZA_OFICINA_REGISTRO);

ALTER TABLE REGISTRO_PUBLICO
ADD CONSTRAINT AK_REGISTRO_PUBLICO UNIQUE(POSTIZA_OFICINA_REGISTRO);












